package com.isima.zzdrive.jpa;
// Generated 4 mars 2014 11:25:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name="file"
    ,catalog="zzdrive"
)
public class File  implements java.io.Serializable {


     private int idfile;
     private String name;
     private int iddirectory;
     private String type;
     private byte[] content;
     private int idowner;

    public File() {
    }

	
    public File(int idfile, int iddirectory, String type, int idowner) {
        this.idfile = idfile;
        this.iddirectory = iddirectory;
        this.type = type;
        this.idowner = idowner;
    }
    public File(int idfile, String name, int iddirectory, String type, byte[] content, int idowner) {
       this.idfile = idfile;
       this.name = name;
       this.iddirectory = iddirectory;
       this.type = type;
       this.content = content;
       this.idowner = idowner;
    }
   
     @Id 
    
    @Column(name="idfile", unique=true, nullable=false)
    public int getIdfile() {
        return this.idfile;
    }
    
    public void setIdfile(int idfile) {
        this.idfile = idfile;
    }
    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="iddirectory", nullable=false)
    public int getIddirectory() {
        return this.iddirectory;
    }
    
    public void setIddirectory(int iddirectory) {
        this.iddirectory = iddirectory;
    }
    
    @Column(name="type", nullable=false)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="content")
    public byte[] getContent() {
        return this.content;
    }
    
    public void setContent(byte[] content) {
        this.content = content;
    }
    
    @Column(name="idowner", nullable=false)
    public int getIdowner() {
        return this.idowner;
    }
    
    public void setIdowner(int idowner) {
        this.idowner = idowner;
    }




}


